"""initial schema

Revision ID: 9a477d9ad3f5
Revises:
Create Date: 2026-07-30 17:01:36.489708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import chain_health.db.types

# revision identifiers, used by Alembic.
revision: str = "9a477d9ad3f5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("created_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.Column("current_group_id", sa.Integer(), nullable=True),
        sa.Column("pinned_message_id", sa.Integer(), nullable=True),
        sa.Column("last_reminder_sent_dt", sa.Date(), nullable=True),
        sa.Column("invited_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.id"], name=op.f("fk_users_invited_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("default_cycle_limit_km", sa.Float(), nullable=False),
        sa.Column("created_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_groups_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
    )
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_groups_user_id"), ["user_id"], unique=False)

    op.create_table(
        "invites",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.Column("expires_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.Column("used_by", sa.Integer(), nullable=True),
        sa.Column("used_at", chain_health.db.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_invites_created_by_users")
        ),
        sa.ForeignKeyConstraint(["used_by"], ["users.id"], name=op.f("fk_invites_used_by_users")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_invites")),
    )
    op.create_table(
        "chains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cycle_limit_km", sa.Float(), nullable=False),
        sa.Column("resource_km", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_retired", sa.Boolean(), nullable=False),
        sa.Column("retired_at", chain_health.db.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_chains_group_id_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chains")),
    )
    with op.batch_alter_table("chains", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chains_group_id"), ["group_id"], unique=False)
        batch_op.create_index(
            "ix_chains_one_active_per_group",
            ["group_id"],
            unique=True,
            sqlite_where=sa.text("is_active"),
        )

    op.create_table(
        "rides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("ride_dt", sa.Date(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("created_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.id"], name=op.f("fk_rides_chain_id_chains")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_rides_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rides")),
        sa.UniqueConstraint("source", "external_id", name="uq_rides_source_external_id"),
    )
    with op.batch_alter_table("rides", schema=None) as batch_op:
        batch_op.create_index("ix_rides_chain_created", ["chain_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_rides_chain_id"), ["chain_id"], unique=False)
        batch_op.create_index("ix_rides_chain_ride_dt", ["chain_id", "ride_dt"], unique=False)
        batch_op.create_index("ix_rides_user_created", ["user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_rides_user_id"), ["user_id"], unique=False)

    op.create_table(
        "rotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("activated_at", chain_health.db.types.UTCDateTime(), nullable=False),
        sa.Column("activated_dt", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"], ["chains.id"], name=op.f("fk_rotations_chain_id_chains")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_rotations_group_id_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rotations")),
    )
    with op.batch_alter_table("rotations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_rotations_chain_activated", ["chain_id", "activated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rotations_chain_id"), ["chain_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rotations_group_id"), ["group_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rotations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rotations_group_id"))
        batch_op.drop_index(batch_op.f("ix_rotations_chain_id"))
        batch_op.drop_index("ix_rotations_chain_activated")

    op.drop_table("rotations")
    with op.batch_alter_table("rides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rides_user_id"))
        batch_op.drop_index("ix_rides_user_created")
        batch_op.drop_index("ix_rides_chain_ride_dt")
        batch_op.drop_index(batch_op.f("ix_rides_chain_id"))
        batch_op.drop_index("ix_rides_chain_created")

    op.drop_table("rides")
    with op.batch_alter_table("chains", schema=None) as batch_op:
        batch_op.drop_index("ix_chains_one_active_per_group", sqlite_where=sa.text("is_active"))
        batch_op.drop_index(batch_op.f("ix_chains_group_id"))

    op.drop_table("chains")
    op.drop_table("invites")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_groups_user_id"))

    op.drop_table("groups")
    op.drop_table("users")
    # ### end Alembic commands ###
