"""outbox

Revision ID: b870a3fbbeb4
Revises: ef66139a53a5
Create Date: 2026-08-08 03:56:59.569881

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate emits `chain_health.db.types.UTCDateTime()` in the column
# definition but does not add this import — without it the migration dies with
# NameError on the very first run.
import chain_health.db.types

# revision identifiers, used by Alembic.
revision: str = "b870a3fbbeb4"
down_revision: str | Sequence[str] | None = "ef66139a53a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.String(),
            nullable=False,
            comment="aiogram method class name, e.g. SendMessage",
        ),
        sa.Column("payload", sa.String(), nullable=False, comment="the method serialized as JSON"),
        sa.Column(
            "created_at",
            chain_health.db.types.UTCDateTime(),
            nullable=False,
            comment="UTC instant the promise was made",
        ),
        sa.Column(
            "attempts", sa.Integer(), nullable=False, comment="failed delivery attempts so far"
        ),
        sa.Column(
            "next_attempt_at",
            chain_health.db.types.UTCDateTime(),
            nullable=False,
            comment="UTC instant before which not to retry (backoff)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.create_index("ix_outbox_next_attempt", ["next_attempt_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_outbox_next_attempt")

    op.drop_table("outbox")
    # ### end Alembic commands ###
